apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: system-node-critical
value: 2000000000
globalDefault: false
description: "Used for system critical pods that must not be evicted from a node."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: system-cluster-critical
value: 1000000000
globalDefault: false
description: "Used for system critical pods that must not be evicted from a cluster."
