apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
stringData:
  MYSQL_DATABASE_USER: {{ .Values.mysql.user | quote }}
  MYSQL_DATABASE_PASSWORD: {{ .Values.mysql.password | quote }}
  MYSQL_DATABASE_DB: {{ .Values.mysql.database | quote }}
