apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: flaskapp
  ports:
    - port: {{ .Values.service.port | default 5002 }}
      targetPort: {{ .Values.service.targetPort | default 5002 }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
