replicaCount: 1

image:
  repository: 977098995259.dkr.ecr.eu-west-1.amazonaws.com/my-k8s-cluster-database
  tag: latest
  pullPolicy: IfNotPresent
  private: true

imagePullSecrets:
  - name: regcred
mysql:
  rootPassword: root
  user: root
  password: root
  database: BucketList

storage:
  size: 2Gi
  className: nfs-client 
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

service:
  port: 3306
  type: ClusterIP


