apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-from-ecr-deployment
  labels:
    app: nginx-ecr
spec:
  replicas: 3 # <--- هنا بنحدد إننا عايزين 3 Pods
  selector:
    matchLabels:
      app: nginx-ecr
  template:
    metadata:
      labels:
        app: nginx-ecr
    spec:
      containers:
      - name: nginx
        image: "977098995259.dkr.ecr.eu-west-1.amazonaws.com/my-k8s-cluster-app-repo:latest"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ecr-service
spec:
  selector:
    app: nginx-ecr
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 80 
  type: NodePort 